### ISSUE TITLE
[ Issue ] Very fast and robotic swipes on DPAD

### ISSUE THREAD

**Issue by kirisaki-vk** [Xtr126/XtMapper#10]
XtMapper doesn't work on most of games that I play then I've noticed that WASD and arrow DPADs are mooving very fast so instead of considering them as swipe they are considered to touch by the game or the system (IDK). 
I've noticed too for Sight mode that if you swipe fast , the swipe will be rupted and become touch at a certain moment

**Comment by Xtr126** [comment]
Thank you for the feedback.
Maybe I should make an option for users to adjust delay for WASD keys touch movement to solve the issue of fast swipes detection in some games as you said.

**Comment by Xtr126** [comment]
Closing as implemented in v1.4.1 release.
