### ISSUE TITLE
RightClickMouse

### ISSUE THREAD

**Issue by semoox** [Xtr126/XtMapper#11]
1-can you add right click mouse as a keymap to use it in shooting game
2- limit wasd size
3- enable to free choose any key in keyboard to enable or disable aiming for games

**Comment by semoox** [comment]
thanks for add right click mouse as a keymap...but there is a small problem..
when using right-click mouse as a keymap  its also unlock crosshair shooting mode when active aim with ~ key grave Which make right-click mouse keymap unusable

**Comment by Xtr126** [comment]
> thanks for add right click mouse as a keymap...but there is a small problem.. when using right-click mouse as a keymap its also unlock crosshair shooting mode when active aim with ~ key grave Which make right-click mouse keymap unusable

You can disable right click for mouse aim from settings

**Comment by semoox** [comment]
I tried It many time but not work also I tried to remove right click mouse from source code and build app with android studio and sucessful build but right click mouse do the same thing when active crosshair with key grave ~ and add right click mouse as a keymap its also disable aiming for cross hair

**Comment by Xtr126** [comment]
Thanks for reporting, it should be fixed now.
