### ISSUE TITLE
Interface layout it is also possible to optimize

### ISSUE THREAD

**Issue by guobao2333** [Xtr126/XtMapper#116]
Here are a few suggestions:

1. There should be some distance between the `Add Games` button in the lower right corner and the corner of the screen, maybe 5-20px is good.
2. When clicking the `Add Games` button to start retrieving all the apps, which can cause lag on some devices, you can usually add a "loading" prompt message, or you can also retrieve the apps in the background when you open them or after you open them, which has a significant effect on increasing the user experience.
3. The description and buttons in the setup should be sorted close to the screen respectively, e.g. the buttons are sorted to the right, rather than following the description.
4. If there are new strings that need to be translated please `@we` so we know you need our help, after all we can't keep an eye on your project all the time.

**Comment by Xtr126** [comment]
1. Sure, I'd admit that I'm not good at UIs, thanks for the suggestion.
2. Fine, we will use a loading indicator, just like Android settings does.
3. If you mean the keymap editor, a new UI for that is already in the development branch.
4. Sorry I've been busy with other projects recently, I'll make sure to @ after getting things done for next release.

**Comment by Xtr126** [comment]
I decide to use [Transifex](https://www.transifex.com/open-source/) for translations

**Comment by guobao2333** [comment]
> I decide to use [Transifex](https://www.transifex.com/open-source/) for translations

OK, I will learn about it when I have time, but I don't know why you chose it...

**Comment by Xtr126** [comment]
> > I decide to use [Transifex](https://www.transifex.com/open-source/) for translations
> 
> OK, I will learn about it when I have time, but I don't know why you chose it...

Becuase they offer a service free for open source projects. But transifex itself is not FOSS.
Weblate is FOSS and offers a free tier with limits for open source projects, I have to explore how well it would integrate with an Android app.

**Comment by guobao2333** [comment]
I think Crowdin is also a good choice, many projects choose it. :)  
There are so many translators like me working regularly on `Crowdin` that the advantages of `Transifex` may not be obvious.

**Comment by guobao2333** [comment]
Crowdin like Transifex, provides free services for open source projects, such as Minecraft used its services, which supports Android applications very well, providing contextual reference and automatic calibration. (Although the calibration for Chinese is not done well...) So I still recommend Crowdin.

**Comment by Xtr126** [comment]
Crowdin had some criteria https://crowdin.com/page/open-source-project-setup-request that I was not sure I can meet so I was reluctant to choose it. But anyway as you recommend it I will send them a request and see.

**Comment by Xtr126** [comment]
Our crowdin page is live now! https://crowdin.com/project/xtmapper
Their GitHub integration didn't work or it requires more configuration but I dealt it by using the github action instead.

**Comment by Xtr126** [comment]
@guobao2333   We are nearing next release and it would be nice to have the translations complete. Some new strings were added  https://github.com/Xtr126/XtMapper/blob/dev/app/src/main/res/values-zh-rCN/strings.xml
Also #118 #106

**Comment by guobao2333** [comment]
So should I continue to submit translations through the **frok repository**, or translate through **Crowdin**?

Although I have submitted some of my translations on Crowdin, I still need to confirm them to avoid wasting time and doing more work :)

**Comment by guobao2333** [comment]
I think I can combine these two methods to increase my work efficiency, although I don't feel the difference 😂
Because I may need to check whether the translation is appropriate in conjunction with CI build, but this will make my workflow very strange, because I may need to do duplicate work in Crowdin and Github :(

**Comment by Xtr126** [comment]
The crowdin translations are updated now #132 
I had to run the GitHub action.
Feel free to contribute using whatever platform you prefer, appreciate it.
