### ISSUE TITLE
There are two key mapping problems in the game to give feedback!

### ISSUE THREAD

**Issue by kahunama** [Xtr126/XtMapper#12]
1、When setting the key mapping, it often occurs that the button is deleted, and the button cannot be saved after resetting the button. At this time, there is no response to exiting the button APP。
     i can only use the process manager to force the end, otherwise nothing will work, and then restart the APP to normal. The same problem will occur again if you perform the previous operation!
2、In many games such as Blade&Soul Revolution, the game screen is completely black when the button is switched to map, and the game screen is normal when the button is stopped. 
    Only use a tape measure to measure the position. In this way, i can set the button position to play the game.

My game environment runs under android 9 amd rx550 2G vulkan. Tried the same in normal mode.
![Screenshot_20230329-225356](https://user-images.githubusercontent.com/105717872/228627196-0434d210-c769-4282-a90b-38eebc0b6dbf.png)

**Comment by Xtr126** [comment]
> 1、When setting the key mapping, it often occurs that the button is deleted, and the button cannot be saved after resetting the button. At this time, there is no response to exiting the button APP。 i can only use the process manager to force the end, otherwise nothing will work, and then restart the APP to normal. The same problem will occur again if you perform the previous operation! 2、In many games such as Blade&Soul Revolution, the game screen is completely black when the button is switched to map, and the game screen is normal when the button is stopped. Only use a tape measure to measure the position. In this way, i can set the button position to play the game.
> 
> My game environment runs under android 9 amd rx550 2G vulkan. Tried the same in normal mode. 

1 . Should be fixed in latest APK from [GitHub actions](https://github.com/Xtr126/XtMapper/actions)
2. While playing the game drag down the notification panel and tap on the notification to edit keymap or setup a keyboard shortcut for it in settings.

**Comment by kahunama** [comment]
1、Thank you very much, everything works fine with version 1.4.1(6) key mapping.
2、Regarding the problem of the black screen, there is no problem to click and modify it with the notification bar.
![Screenshot_20230330-213634](https://user-images.githubusercontent.com/105717872/228854209-0c3a155c-40a2-489d-9c59-8c7c7a2d7cc8.png)
3、There is another problem, I am under android x86 9.0 r2, the installation of the new version must be in the kernel mode of Linux-Kernel_5.18.0-android-x86_64_Xtr.gxp, the keyboard and key functions can be activated,。xtMapper.sh will also exist
       after the installation of the application is completed, replace it with another Kernel, such as GoogleLTS_xanmod1._Kernel_5.10.9_pledge.gxp is no problem.
        My intel ax200 wireless network card must work under this kernel（GoogleLTS_xanmod1._Kernel_5.10.9_pledge）. When working with the built-in network card, there will be virtwifi. The network speed response in this mode is a bit slow!

**Comment by Xtr126** [comment]
> 1、Thank you very much, everything works fine with version 1.4.1(6) key mapping. 2、Regarding the problem of the black screen, there is no problem to click and modify it with the notification bar.  3、There is another problem, I am under android x86 9.0 r2, the installation of the new version must be in the kernel mode of Linux-Kernel_5.18.0-android-x86_64_Xtr.gxp, the keyboard and key functions can be activated,。xtMapper.sh will also exist after the installation of the application is completed, replace it with another Kernel, such as GoogleLTS_xanmod1._Kernel_5.10.9_pledge.gxp is no problem. My intel ax200 wireless network card must work under this kernel（GoogleLTS_xanmod1._Kernel_5.10.9_pledge）. When working with the built-in network card, there will be virtwifi. The network speed response in this mode is a bit slow!


You can disable virtwifi by adding `VIRT_WIFI=0` to parameters list in linux kernel command line in your grub config.
