### ISSUE TITLE
Keyboard events stop whenever mouse move or click

### ISSUE THREAD

**Issue by shadichy** [Xtr126/XtMapper#13]
Whenever im WASD'ing, moving mouse just for 1px will stop WASD movement instantly

**Comment by Xtr126** [comment]
This is an Android framework limitation in that it doesn't support mouse and touch events at the same time, happens even with a real touchscreen. In Android if you press and hold a finger on touchscreen and try to move the mouse simultaneously the tap event will stop. For the keymapper we could workaround this by halting sending mouse events for the moment or if you launch the remote with only adb shell privileges which will use an application overlay to display a cursor and no conflict then.

**Comment by shadichy** [comment]
> This is an Android framework limitation in that it doesn't support mouse and touch events at the same time, happens even with a real touchscreen. In Android if you press and hold a finger on touchscreen and try to move the mouse simultaneously the tap event will stop. For the keymapper we could workaround this by halting sending mouse events for the moment or if you launch the remote with only adb shell privileges which will use an application overlay to display a cursor and no conflict then.

how about simulate mouse click as touch?

**Comment by shadichy** [comment]
> how about simulate mouse click as touch?

first, disable system's click as touch simulation, so you can use your own implementation
and then, implement it, just like phoenix os's game helper (octopus)

**Comment by Xtr126** [comment]
> > how about simulate mouse click as touch?
> 
> first, disable system's click as touch simulation, so you can use your own implementation and then, implement it, just like phoenix os's game helper (octopus)

That works but Bliss, Prime OS and phoenix OS did it by modifying AOSP source code. At the moment I have no idea on how to do it with a user app.
Anyway the issue has been fixed in v2.0 release by using application overlay instead of emulating a mouse device.
