### ISSUE TITLE
[Issue] Right mouse button click is deactivating shooting mode instead of doing what it should

### ISSUE THREAD

**Issue by ComValer** [Xtr126/XtMapper#15]
In both 1.4 and 1.4.1 versions, if you click right mouse button when the shooting mode is working - it will only deactivate shooting mode Whatever the settings are (even if you set ~ as a shooting mode controlling key in both app menu and map 's one .) So when in shooting mode - the right button map won't work as intended

**Comment by Xtr126** [comment]
Thanks for reporting, it should be fixed now. Try latest APK from GitHub actions
