### ISSUE TITLE
[Issue] Input delay in 1.4.1

### ISSUE THREAD

**Issue by ComValer** [Xtr126/XtMapper#16]
It's checked that on 1.4.1 all the mapped signals are registered Later than they were in 1.4 and the other versions for about 50-100ms which is pretty much noticeable, especially in rhythm games. Dpad element usage starts even later and somehow slower (it's literally might be noticed how the virtual con starts moving from the center💀)

Lenovo IdeaPad S145 81MV : Bliss OS 14.10, Bliss OS 15.8.5 - integrated keyboard, USB keyboard, USB mouse

**Comment by Xtr126** [comment]
Is it the same even if you set swipe delay to 0 in settings ?

**Comment by malhotrafaiz94** [comment]
hello 
i have random crash or frezze of cursor when click to start

**Comment by AndrowsAIO** [comment]
you need fix right click cancel .aim .hide

because .in .shooter .game .we .using .right .click .for zoom

change .that .with .other  .button .like .'ctrl '.or  .' ~ '.only

**Comment by ComValer** [comment]
> Is it the same even if you set swipe delay to 0 in settings ?

Yes, saying it was 0 by default and the registering delay presenting at that moment too. When the 100 and basically other value is set - nothing really changes in terms of the delay .
But the most frustrating one is the dpad slowness that appeared .. because it really breaks some situations like it may not even trigger the control on quick moves .. .🤖☠️💀💀

**Comment by Xtr126** [comment]
Performance has been improved in v2.0 release.
