### ISSUE TITLE
[Feature request] Reduce slider step for Dpad radius and swipe delay to 0.05 and 5ms and/or add input box right next to the slider for manual input value

### ISSUE THREAD

**Issue by shadichy** [Xtr126/XtMapper#17]
For me, 100ms seems too much, so i forked your repo and modified a little bit. I found out 25ms suits me most, so please do it. Thanks

**Comment by Xtr126** [comment]
Solved in  https://github.com/Xtr126/XtMapper/commit/3536d1aceed1048e2a22eda2350396ddffb9e147
