### ISSUE TITLE
[Feature request] Ability to temporarily disable keymapping (shortcut/for text input)

### ISSUE THREAD

**Issue by shadichy** [Xtr126/XtMapper#18]

**Comment by ilhan-athn7** [comment]
I went to open an issue for same context.
Here is my idea;

When you go `Settings` > `System` > `Languages & input` > `On-screen keyboard` we should able to add XtMapper in and set it default.
XtMapper should be trigerred when fronted app request keyboard for text input.

This way user won't need to toggle keymapping on it's own (still better to have a option).

```As a workaround, you can use "Switch Profile" feature.```

**Comment by Xtr126** [comment]
Good suggestion, I will work on it for next release.

**Comment by selurvedu** [comment]
Fixed in 2.0?

**Comment by ilhan-athn7** [comment]
> Fixed in 2.0?

Yes, if you enable xtmapper as default on-screen keyboard, mapping will be paused when text input requested.

**Comment by Xtr126** [comment]
> > Fixed in 2.0?
> 
> Yes, if you enable xtmapper as default on-screen keyboard, mapping will be paused when text input requested.

And if you are using a physical keyboard, show virtual keyboard must be enabled.
