### ISSUE TITLE
[Feature request] Option for Shooting mode activation while specific key pressed

### ISSUE THREAD

**Issue by ComValer** [Xtr126/XtMapper#19]
It would be cool if aside  with the implemented On Key - Switch Method  would be added a method to enable shooting mode While the chosen key is pressed.
Also here should be a combobox for an option to Invert the Trigger (for shooting mode to work all the time While the Key Is Not pressed, and deactivating when It Is (example.: Windows Genshin Impact version Pointer - It appears Only While Alt key is pressed)

**Comment by Xtr126** [comment]
This doesn't look like a very useful feature for me, but it has been implemented and will be available in next release.
Thank you for opening this issue and bringing this into attention.

**Comment by ilhan-athn7** [comment]
Well, tbh i did not like genshin impact ALT key behaviour, it should let me use mouse without holding ALT key.

> It would be cool if aside with the implemented On Key - Switch Method would be added a method to enable shooting mode While the chosen key is pressed. Also here should be a combobox for an option to Invert the Trigger (for shooting mode to work all the time While the Key Is Not pressed, and deactivating when It Is (example.: Windows Genshin Impact version Pointer - It appears Only While Alt key is pressed)
