### ISSUE TITLE
[Issue] Auto-activation option availability is inconsistent even when the Root is given

### ISSUE THREAD

**Issue by ComValer** [Xtr126/XtMapper#20]
An app seem to suppose to Auto-Activate the service when the Root is given to it, but for some reason it doesn't. The Auto-Activate is Disabled most of the time, but may get Available under unknown circumstances.

(The ones registered are: It Enabled when the app gone Splitscreen after Fullscreen (happened only 1 time of 6 tries), and It also did when the App have crashed and restarted after service broke and I attempted to Stop (happened 2 times of ~12 tries)

**Comment by kahunama** [comment]
I also have this problem. I can click auto-activation when I start android for the first time. Sometimes it stops halfway or for other reasons, it is gray, but it does not affect the use of key mapper. Restarting the computer still works.

**Comment by Xtr126** [comment]
Auto-activate button will be disabled when the keymapper is already activated and the remote service is running.

**Comment by ComValer** [comment]
> Auto-activate button will be disabled when the keymapper is already activated and the remote service is running.
Sorry  just understood this .*facepalm*
