### ISSUE TITLE
Unable To Use Non Number and Alphabetic keyboard button For Keymap

### ISSUE THREAD

**Issue by semarainc** [Xtr126/XtMapper#3]
Hi,
thank you for your awesome project :D

i'm having a problem not able to use space key when mapping my keyboard event

Step To Reproduce:
1) Open XtMapper
2) Edit Overlay
3) Click Pencil Button on bottom right corner
4) Add Key, then a button will shown to the screen
5) Click the button, then press any key (in this case "Space button")

Expected Result
It Will show "Space" when after pressing space key, just like pressing B, button will show "B" text

Observed Result
Nothing Happen, the button showing "A" button unchanged

Additional Information:
OS: Bliss OS 14.x running on QEMU/KVM
Graphics: Virtio with 3d Acceleration (Shown in Virt-Manager)
For Mouse and keyboard : i'm using USB mouse and USB Keyboard from Virt-Manager Setting

I Hope you could look into this issue
thanks for your effort :D

**Comment by Xtr126** [comment]
Thank you for the report, the ability to add CTRL, SPACE and other keys will be in next release.
This issue should be resolved as of commit https://github.com/Xtr126/XtMapper/commit/d538dbf37afbca92cd4267d0b3eb9bce86997726.
