### ISSUE TITLE
What about mouse acceleration???

### ISSUE THREAD

**Issue by Yuva-Andrez** [Xtr126/XtMapper#30]

**Comment by Xtr126** [comment]
Mouse acceleration is not good for gaming (especially FPS games). From settings you can increase mouse speed if desired.

**Comment by Yuva-Andrez** [comment]
Yes but i wonder lot of Configuration especially mouse x,y sensitive and mouse acceleration control are available windows pls take it to android plz😢

**Comment by Yuva-Andrez** [comment]
I can help you whatever i can plz build the bestest one

**Comment by Yuva-Andrez** [comment]
I turned off but after 5 few sec since mouse locked it increases auto     i dont know how to understand that is that is mouse accel or something i feel in i play freefire after i locked mouse it means touch starts when mouse weere locked and touch is not released so (in some games when we play eith continous touch it camera will rotate madly) but after releasing and locking it is perfectly fine but i cant do it when fighting seriously with  enimy 😢

**Comment by Yuva-Andrez** [comment]
Now all i talkin abt octopus kemapper 1.0  i think u can help us we tooo help u up(we == there are lot of people like me)

**Comment by Xtr126** [comment]
You will have to contact octopus keymapper developers regarding that. I don't have access to octopus keymapper source code to alter its behavior.

**Comment by Xtr126** [comment]
Closing as stale issue.
