### ISSUE TITLE
XtMapper Crash when Switching Profile

### ISSUE THREAD

**Issue by semarainc** [Xtr126/XtMapper#4]
Hi
thanks for your in to this project :D , this helps me a lot when playing android game from my linux laptop ^_^

i've encountered issue regarding profile switching, the app suddenly crash when switching profile

Step to Reproduce:
1) Open XtMapper
2) Use Default Profile
3) Create Overlay
4) Use The overlay to play games
5) back to XtMapper
6) Switch Profile to random apps
7) The app crash

Observed Result
- The app crash

Expected Result
- The app doesn't crash

Additional Information:
OS : Bliss OS 14.x running in QEMU/KVM (Virt-Manager)
Graphics: Virtio with 3D Acceleration
Keyboard and Mouse Setting: Using USB keyboard + USB Mouse from Virt-Manager Setting

I Hope you don't mind to look on this issue
Thanks for your effort

**Comment by Xtr126** [comment]
Thank you for reporting, I will look into it as soon as possible. 
I will redesign profiles later, current way is not very intuitive. 
And make it possible to switch profiles while in-game.

**Comment by Xtr126** [comment]
Closing as fixed in v1.4
