### ISSUE TITLE
Moving mouse cancels shooting mode

### ISSUE THREAD

**Issue by niru64** [Xtr126/XtMapper#40]
I am using `scrcpy --otg` to pass the mouse and the keyboard to my mobile device, when I enable shooting mode, the keyboard inputs work all fine but as soon as I move my mouse it stops accepting keyboard inputs and I have to re-enable shooting mode again for it to work.
Mind you I am not using BlissROM, but rather using AOSPA Android 13 on a POCO X3 NFC (surya).
If there were any troubleshooting steps or such, or some issue template, I'd fill it out, but I'll wait for a response. Thank you.

**Comment by Xtr126** [comment]
> I am using `scrcpy --otg` to pass the mouse and the keyboard to my mobile device, when I enable shooting mode, the keyboard inputs work all fine but as soon as I move my mouse it stops accepting keyboard inputs and I have to re-enable shooting mode again for it to work. Mind you I am not using BlissROM, but rather using AOSPA Android 13 on a POCO X3 NFC (surya). If there were any troubleshooting steps or such, or some issue template, I'd fill it out, but I'll wait for a response. Thank you.

It could be that mouse capture isnt working as intended on your system and mouse events conflict with touch events as in #13 
I can't reproduce the issue, running Bliss OS with keyboard and mouse attached:
![Screenshot_20230813-100242_Settings](https://github.com/Xtr126/XtMapper/assets/80520774/b04fada7-d153-4f4a-96d1-7db621d63fde)
I will try with scrcpy --otg later

**Comment by Xtr126** [comment]
scrcpy —otg and aiming mode works fine now.
