### ISSUE TITLE
How does Left Click and Right Click remap work?

### ISSUE THREAD

**Issue by developer-swetabh** [Xtr126/XtMapper#45]
Hi,
I was trying to run this application in an Android based Laptop and exploring the features.
I was able to map click events to keys, add swipe behavior and was able to add the D-pad keys, but one thing I could not understand  how left click and right click mapping is done. 

I have added a left click and right click to a button, but when i try to perform a left click any where, click/touch event is not triggering to that location.

It would be much helpful if anyone can guide me to this.

**Comment by Xtr126** [comment]
How to use it is explained in the docs (Aiming mode): https://xtr126.github.io/XtMapper-docs
