### ISSUE TITLE
Issue about wayland-getevent

### ISSUE THREAD

**Issue by InternetRebelAKAQuachHungPhong** [Xtr126/XtMapper#48]
So, I used all exact methods of using wayland-getevent but it didn't work for the latest release APK, but did for the debug one from Actions, but the debug one I at first thought won't work because keys for buttons won't change, but it would if I press the "XtMapper" window over the Waydroid one
What do you guys think?
This experimental project seems good and it's pretty cool they got serious about the issue #9, just want to say
Maybe the next APK going this progress may be labeled at least Pre-release
Any issues so far when "waydroid-getevent" was around, guys?
You want or need me to send you a footage of screen record recording the process?

**Comment by Xtr126** [comment]
> but it would if I press the "XtMapper" window over the Waydroid one

It will have to be like that as waydroid or wayland doesn't provide a API or something for a tool like a keymapper (X11 theoretically does), so we have to rely on this hack.

> Maybe the next APK going this progress may be labeled at least Pre-release

I was thinking of next release after integrating documentation into the app and also making it a bit more user-friendly. 
Use this link for now: https://github.com/Xtr126/XtMapper/issues/35#issuecomment-1703947944 

> You want or need me to send you a footage of screen record recording the process?

As you wish, but the process may change in the future and become outdated.

**Comment by Xtr126** [comment]
Closing as unimportant.
