### ISSUE TITLE
[Enhancement] Request immersive mode on keymap editor

### ISSUE THREAD

**Issue by ilhan-athn7** [Xtr126/XtMapper#50]
System navbar is preventing to place hovering buttons at the bottom of screen, keymap editor need to be fullscreen.

**Comment by Xtr126** [comment]
Keymap editor is an APPLICATION_OVERLAY, not a valid Activity. Only Activities can be fullscreen in Android. So immersive mode must be triggered by app running in foreground (the game) or at system level.
But now I got an idea, I can make it to be an floating type activity with transparent window background. Thanks for filing the issue.

**Comment by Xtr126** [comment]
Issue has completely resolved in commit https://github.com/Xtr126/XtMapper/commit/7ecf23687c9147bc6468a673c1a786f02cfbce44. Closing this issue.
