### ISSUE TITLE
latest version does not detect kernel su root on bliss os 14.10 android 11 x86

### ISSUE THREAD

**Issue by Sheepmister** [Xtr126/XtMapper#52]
help

**Comment by Xtr126** [comment]
This might have happened after KernelSU updates, ignore that message for now (the keymapper still can use root and work fine).  I'll do something later.

**Comment by Xtr126** [comment]
It might be a bug in old kernelSU version used in Bliss 14.10. For now open termux app, type `su` and enter and you can enter a root shell in which you can run the script to activate XtMapper. https://xtr126.github.io/XtMapper-docs/guides/activation/

**Comment by Xtr126** [comment]
Closing as fixed in v2.1.0
