### ISSUE TITLE
Constantly asking about creating new profiles

### ISSUE THREAD

**Issue by MurderAxolotl** [Xtr126/XtMapper#53]
When switching between apps (even into XtMapper itself) it constantly asks if I want to make a new profile

Hitting "Cancel"... it pretends like I hit "OK" and asks me for a profile name. I can close out at this point, which normally would be fine.
But the SECOND I switch to a different app, it just pops back up again

If it matters, I'm running under Waydroid, using [this build](https://github.com/Xtr126/XtMapper/actions/runs/6511031611) of the APK, and using Wayland GetEvent tool for keyboard / mouse support

**Comment by Xtr126** [comment]
Thanks for the feedback, I will try to add an option to disable auto-profile creating.

**Comment by Xtr126** [comment]
Closing as resolved in v2.1.0 release
