### ISSUE TITLE
"This application was not installed"

### ISSUE THREAD

**Issue by MarddleDoo12** [Xtr126/XtMapper#57]
I don't know why it won't let me install, I'm 32-bit (motorola G6 play)

**Comment by Xtr126** [comment]
You will have to edit abiFilters here https://github.com/Xtr126/XtMapper/blob/dev/app/build.gradle#L18  and set it to 'armeabi-v7a' and compile the APK yourself

**Comment by MarddleDoo12** [comment]
okay, and how do I compile it? Do I pack everything and sign it?

**Comment by Xtr126** [comment]
> okay, and how do I compile it? Do I pack everything and sign it?

Signing should not be required, just run `./gradlew assembleDebug` or `./gradlew.bat assembleDebug` and the compiled APK will be in `app/build/outputs/apk/debug/app-debug.apk`.
Alternatively you can fork this repository and use github actions to build it (with the edited build.gradle).
