### ISSUE TITLE
 android x86 9 xtmapper problem

### ISSUE THREAD

**Issue by kahunama** [Xtr126/XtMapper#6]
After android x86 9 xtmapper is installed, the interface opens normally, click active with su and then click overlay prompt to reactivate. When searching /storage/emulated/0/Android/data/xtr.keymapper/files in the file manager, xtmapper.sh is not found, and xtmapper cannot work!
The same is true for reinstalling xtmapper!
I don't know what the problem is, it's the same in several versions.

**Comment by Xtr126** [comment]
I have also experienced this problem in certain Android ROMs, sometimes restarting the app fixes it. But it didn't happen in Bliss OS so I didn't care about it that much. 
I will look into this issue, thanks for your report. 
You could also run this command  `chmod 777 -R /storage/emulated/0/Android/data/xtr.keymapper` and try again. 
If the script wont get written at all, use this command in terminal with root (su) to run the remote service `env LD_LIBRARY_PATH=$(echo /data/app/*/xtr.keymapper*/lib/x86_64) CLASSPATH=$(echo /data/app/*/xtr.keymapper*/base.apk) /system/bin/app_process /system/bin xtr.keymapper.server.InputService`

**Comment by kahunama** [comment]
> I have also experienced this problem in certain Android ROMs, sometimes restarting the app fixes it. But it didn't happen in Bliss OS so I didn't care about it that much. I will look into this issue, thanks for your report. You could also run this command `chmod 777 -R /storage/emulated/0/Android/data/xtr.keymapper` and try again. If the script wont get written at all, use this command in terminal with root (su) to run the remote service `env LD_LIBRARY_PATH=$(echo /data/app/*/xtr.keymapper*/lib/x86_64) CLASSPATH=$(echo /data/app/*/xtr.keymapper*/base.apk) /system/bin/app_process /system/bin xtr.keymapper.server.InputService`

Still the same problem, but I found a problem after deleting and reinstalling, I don't know if it has something to do with it.

![Screenshot_20230228-234140](https://user-images.githubusercontent.com/105717872/221905550-aedc8887-53a4-4ce3-b12d-90c792eedb9a.png)

**Comment by Xtr126** [comment]
Commit https://github.com/Xtr126/XtMapper/commit/86721e28325fac3d60c423e55c9e225dd787b3b9 fixes your issue hopefully. Closing this for now.

**Comment by kahunama** [comment]
After installing xtmapper1.4, the problem is the same as before. The files generated in the directory are as follows:

![Screenshot_20230309-022235](https://user-images.githubusercontent.com/105717872/223801321-1153ebd1-75cb-41b2-b2b3-afc2f2d629e9.png)

**Comment by Xtr126** [comment]
> After installing xtmapper1.4, the problem is the same as before. The files generated in the directory are as follows:
> 
> ![Screenshot_20230309-022235](https://user-images.githubusercontent.com/105717872/223801321-1153ebd1-75cb-41b2-b2b3-afc2f2d629e9.png)

Can you also try with this APK?
[xtmapper.zip](https://github.com/Xtr126/XtMapper/files/10934101/xtmapper.zip)

If nothing works use this command in a root shell instead to activate:
```
env LD_LIBRARY_PATH=$(echo /data/app/*/xtr.keymapper*/lib/x86_64) CLASSPATH=$(echo /data/app/*/xtr.keymapper*/base.apk) /system/bin/app_process /system/bin xtr.keymapper.server.InputService
```

**Comment by kahunama** [comment]
Thank you very much for your hard work！ now android x86 9.0 r2 finally works. I used the latest 1.4(5) you sent.
Has been successfully run in an arcade game.

![Screenshot_20230313-002912](https://user-images.githubusercontent.com/105717872/224558545-e3a713d5-97e4-4525-9cd6-69b37ed208b9.png)
![Screenshot_20230313-005855](https://user-images.githubusercontent.com/105717872/224560072-bdf6dcea-4d4f-4361-8ebb-9e8d61ab6839.png)
![Screenshot_20230313-003340](https://user-images.githubusercontent.com/105717872/224558599-c4db454e-9bf9-4e3a-b7e8-6a4e89c14848.png)
![Screenshot_20230313-005754](https://user-images.githubusercontent.com/105717872/224560036-b00ba54f-ed93-4f0d-a2a3-aaf567d9e88a.png)

**Comment by kahunama** [comment]
In the billiards game in another QQ game, the mouse can also be used as a touch and click. But the mouse pointer is a bit ghosted!

But now it has improved a lot, and it is already available, and there are unexpected surprises. Thank you very much!

![Screenshot_20230313-005015](https://user-images.githubusercontent.com/105717872/224559666-8ed6b9f1-9083-460b-8a02-67b94f9e8262.png)

**Comment by Xtr126** [comment]
Good to know that it works now. Thank you for testing
