### ISSUE TITLE
Support for waydroid (not dupplicate)

### ISSUE THREAD

**Issue by afzl-wtu** [Xtr126/XtMapper#68]
Waydroid seriously lacks keymapper. I can see /dev/input in waydroid getting keystroked. Can we not read directly and rempap them through evdev to touch events?

**Comment by Xtr126** [comment]
You are probably looking for the persist.waydroid.uevent property https://docs.waydro.id/usage/waydroid-prop-options
You can recreate /dev/input/eventX in the waydroid container by triggering the uevent
Finding out the correct /dev/input/eventX by
`cat /proc/bus/input/devices`
Assuming we got event4,
`sudo sh -c 'echo add > /sys/class/input/event4/uevent'`

**Comment by afzl-wtu** [comment]
> You are probably looking for the persist.waydroid.uevent property https://docs.waydro.id/usage/waydroid-prop-options You can recreate /dev/input/eventX in the waydroid container by triggering the uevent Finding out the correct /dev/input/eventX by `cat /proc/bus/input/devices` Assuming we got event4, `sudo sh -c 'echo add > /sys/class/input/event4/uevent'`

If so, why xtmapper does not work with wayddroid. ANd hack of overlay windows is applied ?

**Comment by Xtr126** [comment]
> > You are probably looking for the persist.waydroid.uevent property https://docs.waydro.id/usage/waydroid-prop-options You can recreate /dev/input/eventX in the waydroid container by triggering the uevent Finding out the correct /dev/input/eventX by `cat /proc/bus/input/devices` Assuming we got event4, `sudo sh -c 'echo add > /sys/class/input/event4/uevent'`
> 
> If so, why xtmapper does not work with wayddroid. ANd hack of overlay windows is applied ?

It has been confirmed to work on several systems,  there is also a video  https://youtu.be/yvZD2E7kgG0?si=h7e9bps3wGaH5GnL

**Comment by tcguangda** [comment]
![photo_2024-02-25_22-55-16](https://github.com/Xtr126/XtMapper/assets/88199818/17a757c5-a025-4cec-a02d-782ddb1d6d24)

waydroid works, very good!

**Comment by tcguangda** [comment]
![image](https://github.com/Xtr126/XtMapper/assets/88199818/2c345e71-9f26-4d80-9a70-20de80a07f05)

I have only tried the mouse to replace the touch control before. I don’t know why the custom buttons cannot be changed. There is no response when entering numbers or letters.

**Comment by tcguangda** [comment]
sudo pacman -S wayland-protocols libxkbcommon

Okay, forget to install this!

**Comment by mytcgd** [comment]
This method in waydroid has a flaw. It generates a key-press running form externally. When the game itself supports wasd, there will be conflicts and it is inflexible!

**Comment by Xtr126** [comment]
Try using new [cage method](https://github.com/Xtr126/wayland-getevent/blob/main/README-alt.md).
