### ISSUE TITLE
support more keys ( edited )

### ISSUE THREAD

**Issue by semoox** [Xtr126/XtMapper#7]
can you set right click mouse as key to support scope in battle gaming
also can you support change key for aiming 
after build and test new debug app 
for bliss os 11.3 android 9 / bliss os 14 gapps it's crash after first opening but working good after this
edit keys need some improvement ( test for free fire )
mouse not move like freeze  when drag anything like notificaion panel but it do action
aiming mouse works good test for freefire but there's some lag need some improvment

**Comment by Xtr126** [comment]
> can you set right click mouse as key to support scope in battle gaming

Right click mouse key already can be used to toggle mouse aim (crosshair)
> also can you support change key for aiming 

That would be possible.
> after build and test new debug app for bliss os 11.3 android 9 / bliss os 14 gapps it's crash after first opening but working good after this 

You can check logcat when it crashes. 
> edit keys need some improvement ( test for free fire ) 

Thanks for the suggestion, I will try to improve it.
>mouse not move like freeze when drag anything like notificaion panel but it do action 

We have to stop moving the pointer when performing a drag gesture. This seems to be an Android framework limitation (cannot handle touch and mouse input both at the same time well), so the solution was to freeze the mouse pointer when sending touchscreen event. If you launch the remote service (activation) without root privileges but with adb shell user privileges, it will use an overlay instead and then pointer will be visible when click and dragging mouse.

> aiming mouse works good test for freefire but there's some lag need some improvment

This might be the lowest latency I can get for now.

**Comment by Xtr126** [comment]
Closing this issue as the crashing on first start should be fixed now and can customize key used for mouse aim from settings.
