### ISSUE TITLE
Xtmapper always want root even it had.

### ISSUE THREAD

**Issue by orcbolg3612** [Xtr126/XtMapper#74]
I am using blissos 16.9.3. KernelSU work good with all app except xrmapper, xtmapper alway said that it want root access even i enabled it on kernelSU. Also shizuku on waydroid also have this buggy. I can't playgame on xtmapper without xtmapper

**Comment by Xtr126** [comment]
I will fix this issue by using libsu in XtMapper in the next version. Currently if the shell command executed to run the service exits for some reason, it will show a warning "Root access not found".

**Comment by orcbolg3612** [comment]
> I will fix this issue by using libsu in XtMapper in the next version. Currently if the shell command executed to run the service exits for some reason, it will show a warning "Root access not found".



> I will fix this issue by using libsu in XtMapper in the next version. Currently if the shell command executed to run the service exits for some reason, it will show a warning "Root access not found".

Hope you help it works with shizuku on waydroid

**Comment by Xtr126** [comment]
> > I will fix this issue by using libsu in XtMapper in the next version. Currently if the shell command executed to run the service exits for some reason, it will show a warning "Root access not found".
> 
> > I will fix this issue by using libsu in XtMapper in the next version. Currently if the shell command executed to run the service exits for some reason, it will show a warning "Root access not found".
> 
> Hope you help it works with shizuku on waydroid

This is the solution for waydroid currently: https://github.com/Xtr126/wayland-getevent/blob/main/README.md

**Comment by Xtr126** [comment]
Fixed in https://github.com/Xtr126/XtMapper/commit/a09a2ca1a47cb420fcde71de4f133d95cd4054f4
