### ISSUE TITLE
Cant activate XtMapper in Poco F3

### ISSUE THREAD

**Issue by ravillarreal** [Xtr126/XtMapper#76]
**Describe the issue**

I have XTMapper apk downloaded from the releases page installed on my phone
I execute from adb shell the command `adb shell sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh` but it says "Waiting for overlay..." and it closes, then i try to press the "start" button on the app but it says:

`connecting to server...
connection failed
Please retry activation`

**To Reproduce**
1. Execute `adb shell sh /sdcard/Android/data/xtr.keymapper/files/xtMapper.sh` 
2. Click on 'Start' button
3. Select a name for the profile

**Expected behavior**
I expect that the connection success and be able game using the mouse and keyboard

**Screenshots**
![image](https://github.com/Xtr126/XtMapper/assets/29802906/5c0cb90f-2bfc-4364-add2-8c3578d2ddf6)
![image](https://github.com/Xtr126/XtMapper/assets/29802906/7f7bbbed-36e1-4572-9789-b0c55bd9331d)
![image](https://github.com/Xtr126/XtMapper/assets/29802906/bd4d7c90-fd84-4720-b79f-8fb0dfe45582)

**Device (please complete the following information):**
 - OS: Project Elixir ROM version 3.13
 - Android version 13

**Comment by Xtr126** [comment]
It outputs the PID (26561) and exits because the service is already running. Stop it first by running `kill 26561` in adb shell. Also XtMapper currently doesn't work without disabling SELinux, I have been trying to make a workaround by using tcpip to solve the issue.

**Comment by Xtr126** [comment]
https://github.com/Xtr126/XtMapper/releases/tag/v2.1.2
