### ISSUE TITLE
Select app menu doesn't exist in BlissOS Android Go v15.9

### ISSUE THREAD

**Issue by Alpha-Radke** [Xtr126/XtMapper#77]
**Describe the issue**
After Auto Activation is done, clicking ''Start'' will force you to create a profile for the XtMapper app and won't open up the menu to select an app.

**To Reproduce**
1. Click Auto Activate
2. Click Start

**Expected behavior**
Select an app to create a profile

**Device**
 - OS: Bliss Go v15.9
 - Android version: 12

**Comment by Alpha-Radke** [comment]
Adding profile for the game and clicking ''start'' will only detect the forced XtMapper profile. Nothing else can be detected

**Comment by Alpha-Radke** [comment]
![Screenshot_20240203-000331_XtMapper](https://github.com/Xtr126/XtMapper/assets/86568995/e929b1d0-a403-4c65-8504-4d65b086990e)

**Comment by Alpha-Radke** [comment]
While in-game trying to switch profiles or using any shortcuts simply doesn't work as nothing is detected other than the XtMapper app and sometimes the Settings app for some reason.

Notes:
This is probably running with software rendering cuz I have nvidia GTX 1080 and I don't have integrated gpu in my Intel 10th gen i3
Quickstep Launcher keeps crashing in the background with a popup about it

**Comment by Alpha-Radke** [comment]
Disabling Auto Profiling fixed the issue

**Comment by Xtr126** [comment]
> While in-game trying to switch profiles or using any shortcuts simply doesn't work as nothing is detected other than the XtMapper app and sometimes the Settings app for some reason.
> 
> Notes: This is probably running with software rendering cuz I have nvidia GTX 1080 and I don't have integrated gpu in my Intel 10th gen i3 Quickstep Launcher keeps crashing in the background with a popup about it

If it helps, currently by using Bliss OS Zenith and disabling Launcher3, certain Nvidia GPUs can have hardware acceleration using nouveau.
