### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [Xtr126/XtMapper#79]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by Xtr126** [comment]
Hello, thanks for your effort. I will prepare a key and release a proper signed APK as soon as possible after I can get it to work on mobile phones. 
Currently the app works only on PCs or already insecure rooted devices with SELinux disabled so I did not care about it.

**Comment by IzzySoft** [comment]
Thanks for your reply! And thanks for working on it!

> Currently the app works only on PCs or already insecure rooted devices with SELinux disabled so I did not care about it.

Then maybe I should better remove [your app from my repo](https://apt.izzysoft.de/packages/xtr.keymapper) until that's solved – to avoid frustration on the end of those trying it? I'd then re-enable it as soon as you have it ready and let me know.

**Comment by Xtr126** [comment]
> Thanks for your reply! And thanks for working on it!
> 
> > Currently the app works only on PCs or already insecure rooted devices with SELinux disabled so I did not care about it.
> 
> Then maybe I should better remove [your app from my repo](https://apt.izzysoft.de/packages/xtr.keymapper) until that's solved – to avoid frustration on the end of those trying it? I'd then re-enable it as soon as you have it ready and let me know.

Yes I also agree that it should be removed for now, I’ll let you know after I get it solved.

**Comment by IzzySoft** [comment]
Done that now (effective with the next sync in less than 2h from now). Looking forward to your "ready ping" then, wishing you best progress!

**Comment by Xtr126** [comment]
APKs are signed with a release key now.

**Comment by IzzySoft** [comment]
Thanks, that looks good! Added it back, will be available again with the next sync around 7 pm UTC. I had to screenshot the icon however as it cannot be downloaded; if you want me to put a different icon (or some screenshots), I gladly accept the graphics.

Btw, here's the output from my scanner:

```
No offending libs found.


Dangerous Filters:
------------------
android.view.InputMethod

Permissions:
------------
* android.permission.SYSTEM_ALERT_WINDOW
* android.permission.FOREGROUND_SERVICE
* android.permission.FOREGROUND_SERVICE_SPECIAL_USE
* android.permission.POST_NOTIFICATIONS
* android.permission.INTERNET
* android.permission.INJECT_EVENTS
* xtr.keymapper.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION

SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

If you want to have some explanations added to the permissions, especially `SYSTEM_ALERT_WINDOW` (which then would loose its "chocolate" warning color), just let me know. I already did that for `android.view.InputMethod`:

![image](https://github.com/Xtr126/XtMapper/assets/6781438/909e6db9-0528-414d-b96f-bbf0bbcb5690)


That `DEPENDENCY_INFO_BLOCK` blob is easy to get rid of:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by Xtr126** [comment]
> Thanks, that looks good! Added it back, will be available again with the next sync around 7 pm UTC. I had to screenshot the icon however as it cannot be downloaded; if you want me to put a different icon (or some screenshots), I gladly accept the graphics.
> 
> Btw, here's the output from my scanner:
> 
> ```
> No offending libs found.
> 
> 
> Dangerous Filters:
> ------------------
> android.view.InputMethod
> 
> Permissions:
> ------------
> * android.permission.SYSTEM_ALERT_WINDOW
> * android.permission.FOREGROUND_SERVICE
> * android.permission.FOREGROUND_SERVICE_SPECIAL_USE
> * android.permission.POST_NOTIFICATIONS
> * android.permission.INTERNET
> * android.permission.INJECT_EVENTS
> * xtr.keymapper.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION
> 
> SigningBlock blobs:
> -------------------
> 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
> ```
> 
> If you want to have some explanations added to the permissions, especially `SYSTEM_ALERT_WINDOW` (which then would loose its "chocolate" warning color), just let me know. I already did that for `android.view.InputMethod`:
> 
> ![image](https://private-user-images.githubusercontent.com/6781438/306557303-909e6db9-0528-414d-b96f-bbf0bbcb5690.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MTYwNzksIm5iZiI6MTcwODUxNTc3OSwicGF0aCI6Ii82NzgxNDM4LzMwNjU1NzMwMy05MDllNmRiOS0wNTI4LTQxNGQtYjk2Zi1iYmYwYmJjYjU2OTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTE0MjU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWM2MTM0NjU4ZTg5MGNhYTFhMDA3YzdlYWM5NjAyNDU4MmZmNDY5MGMyNGYwZjI2MmUxOTI4MDI5ZmI0NzVlNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ENVDATDAWhi_UufCmW94cLS9hIktTQXPm_NixeDiZQ4)
> 
> That `DEPENDENCY_INFO_BLOCK` blob is easy to get rid of:
> 
> ```groovy-gradle
> android {
>     dependenciesInfo {
>         // Disables dependency metadata when building APKs.
>         includeInApk = false
>         // Disables dependency metadata when building Android App Bundles.
>         includeInBundle = false
>     }
> }
> ```
> 
> For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

Nice!
It would be great if you can use this icon, I think it is of enough quality for a icon: 
![image](https://github.com/Xtr126/XtMapper/assets/80520774/fb0b638f-20b2-47d4-ab3b-7b2039a1bc75)
SYSTEM_ALERT_WINDOW is used to display a pointer on the screen and for showing alert dialogs (to select apps, switch profiles).

**Comment by IzzySoft** [comment]
> It would be great if you can use this icon

Done, thanks! And yes, definitely enough resolution (everything beyond 72x72 is good, 256x256 is very good – and higher is :rocket: – so yours is at least cislunar, at 512x512 I would have had to throttle your drives :stuck_out_tongue_winking_eye:

> `SYSTEM_ALERT_WINDOW`

Thanks, added! That just leaves the `DEPENDENCY_INFO_BLOCK` – maybe a todo item for the next release then? It's currently using "neutral colors", but I might change that to "warning colors" in a few months or so (once I'm through addressing what popped up from the other scans).

![image](https://github.com/Xtr126/XtMapper/assets/6781438/9bc80d64-7bf8-47b7-9b0c-35f197f484ed)

**Comment by Xtr126** [comment]
> > It would be great if you can use this icon
> 
> Done, thanks! And yes, definitely enough resolution (everything beyond 72x72 is good, 256x256 is very good – and higher is 🚀 – so yours is at least cislunar, at 512x512 I would have had to throttle your drives 😜
> 
> > `SYSTEM_ALERT_WINDOW`
> 
> Thanks, added! That just leaves the `DEPENDENCY_INFO_BLOCK` – maybe a todo item for the next release then? It's currently using "neutral colors", but I might change that to "warning colors" in a few months or so (once I'm through addressing what popped up from the other scans).
> 
> ![image](https://private-user-images.githubusercontent.com/6781438/306636350-9bc80d64-7bf8-47b7-9b0c-35f197f484ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1NjY5NDMsIm5iZiI6MTcwODU2NjY0MywicGF0aCI6Ii82NzgxNDM4LzMwNjYzNjM1MC05YmM4MGQ2NC03YmY4LTQ3YjctOWIwYy0zNWYxOTdmNDg0ZWQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjJUMDE1MDQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzBhNzJiNzQ0OTU1NmQzZTg3MWQzZjgzYTYyNWI4Y2FjYWMyMWZjMThhOTEzZjQ5YzEyNDkzOGY3ZjIwODFjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.p6IM23hWEFfOkQOCpnnJqePFdJhX2SHR5TJ2-kXJyUQ)

Thanks!
Sorry I forgot about that, I disabled it now.
For a more accurate description, android.view.InputMethod is used to detect when user is entering input in a text field and disable the service accordingly. I have not documented the feature myself either, it is not prompted by the app, only if the user themselves go to settings and enable it as an Input method.

**Comment by IzzySoft** [comment]
> Sorry I forgot about that, I disabled it now.

Thanks!

> For a more accurate description

There's a little space limitation, so I have to keep the description short. You see about how long it can be in the screenshot above (I'd rather avoid it causing line breaks if I can). Still enough space to make it twice as long as it currently is; "used to detect when user is entering input in a text field and disable the service accordingly" could fit if you want me putting that.

**Comment by Xtr126** [comment]
I understand, then it’s better to leave it as it is. Closing this issue as I made another release with the dependency info changes included. Thanks.

**Comment by IzzySoft** [comment]
Thanks a lot!
