### ISSUE TITLE
[feature] swipe function

### ISSUE THREAD

**Issue by ghost** [Xtr126/XtMapper#8]
First of all thank you for working on this app.

I know that there is support for using mouse as touch input, i haven't tried that yet but i will assume that it can be used for swiping too. 

what i am saying is that it would be nice to have a swipe function mappable to a key, like i pre define swipe position and length and map a key to it and when i press that key, it does the swipe. It will be useful in games like subway surfers where predefined swipes can do the trick.

**Comment by Xtr126** [comment]
Thanks for the suggestion, I will try to provide an option for that in the future if I got time.
You can also just add dpads and use that for swipes, length can also be adjusted.

**Comment by ghost** [comment]
> Thanks for the suggestion, I will try to provide an option for that in the future if I got time. You can also just add dpads and use that for swipes, length can also be adjusted.

oh cool, thanks.

**Comment by Xtr126** [comment]
Closing as implemented in v1.4.1 release.
