### ISSUE TITLE
Mouse Input Lag Issue

### ISSUE THREAD

**Issue by Electro169** [Xtr126/XtMapper#82]
I Faced 2 Major Issues while using XTMapper

**1. After Pressing ~ the camera movement with mouse not working smoothly and skips input 
this is the major issue i faced and making game unplayable 
2. MultiTouch - i am playing pubg and after pressing scope on button and holding fire  button ,then fire button stops and only one bullet get fired .
Ex - You are firing and while firing if you open scope the firing stops automatically** 

i hope you understand these issue and fix in future updates.
Keyboard controls are working perfectly 🔥

**Comment by Electro169** [comment]
I forget to mention one request 🥲 - Please Add Ctrl Key instead of ~ for cursor input in next update .

**Comment by Xtr126** [comment]
> I Faced 2 Major Issues while using XTMapper
> 
> **1. After Pressing ~ the camera movement with mouse not working smoothly and skips input this is the major issue i faced and making game unplayable 2. MultiTouch - i am playing pubg and after pressing scope on button and holding fire button ,then fire button stops and only one bullet get fired . Ex - You are firing and while firing if you open scope the firing stops automatically**
> 
> i hope you understand these issue and fix in future updates. Keyboard controls are working perfectly 🔥

For 1. Please try clicking on the small button next to the crosshair and adjusting the area. 
![image](https://github.com/Xtr126/XtMapper/assets/80520774/7eb53a11-47a1-428a-b90e-91c181880095)
But I will try to make it more configurable in the future.

**Comment by Xtr126** [comment]
> I forget to mention one request 🥲 - Please Add Ctrl Key instead of ~ for cursor input in next update .

You can set any key for mouse aim in settings already: https://xtr126.github.io/XtMapper-docs/settings/shortcuts/  
Ctrl key is reserved as a modifier though.

**Comment by Electro169** [comment]
> > I forget to mention one request 🥲 - Please Add Ctrl Key instead of ~ for cursor input in next update .
> 
> You can set any key for mouse aim in settings already: https://xtr126.github.io/XtMapper-docs/settings/shortcuts/ Ctrl key is reserved as a modifier though.

Ok so please add mouse side button support instead of ctrl

**Comment by Xtr126** [comment]
2. I cannot reproduce on my end
Using this configuration: 
![Screenshot_20240228-215219_XtMapper](https://github.com/Xtr126/XtMapper/assets/80520774/5727bd40-00e5-40d3-af6c-d1c5ea160201)
![Screenshot_20240228-215653_Blissify_Home](https://github.com/Xtr126/XtMapper/assets/80520774/df54888e-69bb-4b83-9e61-4aa55b3ae8ba)
As you can see there are three pointers working simultaneously on the screen. 
Did you mean something else or?

**Comment by Electro169** [comment]
> 2. I cannot reproduce on my end
>    Using this configuration:
>    ![Screenshot_20240228-215219_XtMapper](https://private-user-images.githubusercontent.com/80520774/308635497-5727bd40-00e5-40d3-af6c-d1c5ea160201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzg5NjMsIm5iZiI6MTcwOTEzODY2MywicGF0aCI6Ii84MDUyMDc3NC8zMDg2MzU0OTctNTcyN2JkNDAtMDBlNS00MGQzLWFmNmMtZDFjNWVhMTYwMjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODQ1MjM3ODY1YjljMzYxMTYxZDNhNzhiYzE2NjhkOTE4YzVhNWRiODU2ODNmMzQwZWUxNGNmNmRiYzVlY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M-drj4ObsTKF28WyfxWnAlLV54O21b_Rz1PU5mZymEc)
>    ![Screenshot_20240228-215653_Blissify_Home](https://private-user-images.githubusercontent.com/80520774/308635579-df54888e-69bb-4b83-9e61-4aa55b3ae8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzg5NjMsIm5iZiI6MTcwOTEzODY2MywicGF0aCI6Ii84MDUyMDc3NC8zMDg2MzU1NzktZGY1NDg4OGUtNjliYi00YjgzLTllNjEtNGFhNTViM2FlOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTg4MjM0ZWFhNDRiNDAwYTYxMjllYzUzZTYyM2NmNjEzZDA4Y2ZiNzg0YWYxNTliODBlODYyNWM1MGVmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-5UyscXsKbOHinkLi3uHuXxHMtG35A49DFnY4ubXWc)
>    As you can see there are three pointers working simultaneously on the screen.
>    Did you mean something else or?

Yes facing issue on left right mouse button 
Tomorrow I will share a video 
Ex- holding left button for firing and then opening scope in mid fight by right button stops firing (stops left button )

**Comment by Electro169** [comment]
> > I Faced 2 Major Issues while using XTMapper
> > **1. After Pressing ~ the camera movement with mouse not working smoothly and skips input this is the major issue i faced and making game unplayable 2. MultiTouch - i am playing pubg and after pressing scope on button and holding fire button ,then fire button stops and only one bullet get fired . Ex - You are firing and while firing if you open scope the firing stops automatically**
> > i hope you understand these issue and fix in future updates. Keyboard controls are working perfectly 🔥
> 
> For 1. Please try clicking on the small button next to the crosshair and adjusting the area. ![image](https://private-user-images.githubusercontent.com/80520774/308617275-7eb53a11-47a1-428a-b90e-91c181880095.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxNDIwMzUsIm5iZiI6MTcwOTE0MTczNSwicGF0aCI6Ii84MDUyMDc3NC8zMDg2MTcyNzUtN2ViNTNhMTEtNDdhMS00MjhhLWI5MGUtOTFjMTgxODgwMDk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE3MzUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGFhMTI1ZTkxMDljN2FkZWJhOThkM2Y3ZGFkZmVlODJiNjM0YTk4YzA2YTVmN2VlYzk0NTFiYjBlNTU5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hKxB7ohiekLRKXX5z1gcK9cL_LDDRGw2TsKLilaCsCo) But I will try to make it more configurable in the future

Yes I already adjusted the box on free area and facing the issue I will try to increase the size of box

**Comment by Xtr126** [comment]
> > 3\. I cannot reproduce on my end
> >     Using this configuration:
> >     ![Screenshot_20240228-215219_XtMapper](https://private-user-images.githubusercontent.com/80520774/308635497-5727bd40-00e5-40d3-af6c-d1c5ea160201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzg5NjMsIm5iZiI6MTcwOTEzODY2MywicGF0aCI6Ii84MDUyMDc3NC8zMDg2MzU0OTctNTcyN2JkNDAtMDBlNS00MGQzLWFmNmMtZDFjNWVhMTYwMjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODQ1MjM3ODY1YjljMzYxMTYxZDNhNzhiYzE2NjhkOTE4YzVhNWRiODU2ODNmMzQwZWUxNGNmNmRiYzVlY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M-drj4ObsTKF28WyfxWnAlLV54O21b_Rz1PU5mZymEc)
> >     ![Screenshot_20240228-215653_Blissify_Home](https://private-user-images.githubusercontent.com/80520774/308635579-df54888e-69bb-4b83-9e61-4aa55b3ae8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzg5NjMsIm5iZiI6MTcwOTEzODY2MywicGF0aCI6Ii84MDUyMDc3NC8zMDg2MzU1NzktZGY1NDg4OGUtNjliYi00YjgzLTllNjEtNGFhNTViM2FlOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTg4MjM0ZWFhNDRiNDAwYTYxMjllYzUzZTYyM2NmNjEzZDA4Y2ZiNzg0YWYxNTliODBlODYyNWM1MGVmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-5UyscXsKbOHinkLi3uHuXxHMtG35A49DFnY4ubXWc)
> >     As you can see there are three pointers working simultaneously on the screen.
> >     Did you mean something else or?
> 
> Yes facing issue on left right mouse button Tomorrow I will share a video Ex- holding left button for firing and then opening scope in mid fight by right button stops firing (stops left button )

Now I understand, I will fix it. Left click was intended to be used after activating mouse aim with right click, not before.

**Comment by Electro169** [comment]
> > > 3. I cannot reproduce on my end
> > > Using this configuration:
> > > ![Screenshot_20240228-215219_XtMapper](https://private-user-images.githubusercontent.com/80520774/308635497-5727bd40-00e5-40d3-af6c-d1c5ea160201.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzg5NjMsIm5iZiI6MTcwOTEzODY2MywicGF0aCI6Ii84MDUyMDc3NC8zMDg2MzU0OTctNTcyN2JkNDAtMDBlNS00MGQzLWFmNmMtZDFjNWVhMTYwMjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE5ODQ1MjM3ODY1YjljMzYxMTYxZDNhNzhiYzE2NjhkOTE4YzVhNWRiODU2ODNmMzQwZWUxNGNmNmRiYzVlY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M-drj4ObsTKF28WyfxWnAlLV54O21b_Rz1PU5mZymEc)
> > > ![Screenshot_20240228-215653_Blissify_Home](https://private-user-images.githubusercontent.com/80520774/308635579-df54888e-69bb-4b83-9e61-4aa55b3ae8ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxMzg5NjMsIm5iZiI6MTcwOTEzODY2MywicGF0aCI6Ii84MDUyMDc3NC8zMDg2MzU1NzktZGY1NDg4OGUtNjliYi00YjgzLTllNjEtNGFhNTViM2FlOGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI4VDE2NDQyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOTg4MjM0ZWFhNDRiNDAwYTYxMjllYzUzZTYyM2NmNjEzZDA4Y2ZiNzg0YWYxNTliODBlODYyNWM1MGVmYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-5UyscXsKbOHinkLi3uHuXxHMtG35A49DFnY4ubXWc)
> > > As you can see there are three pointers working simultaneously on the screen.
> > > Did you mean something else or?
> > 
> > 
> > Yes facing issue on left right mouse button Tomorrow I will share a video Ex- holding left button for firing and then opening scope in mid fight by right button stops firing (stops left button )
> 
> Now I understand, I will fix it. Left click was intended to be used after activating mouse aim with right click, not before.

 i make a video and attached the link on the issues for better understanding [https://drive.google.com/file/d/1DEydA5EXYVhh5DrEHzIkoPXG_tIs0ir6/view?usp=sharing](url)
