### ISSUE TITLE
[Q] Does this work on an actual Android device?

### ISSUE THREAD

**Issue by shirooo39** [Xtr126/XtMapper#85]
I'm not seeing any Q&A, so I'm going to just ask it in here.  
- will it work on an actual Android phone?
- if yes, does it support Android 11 up to 14?
- what about custom rom from manufacturers such as HyperOS? will it still work?

**Comment by Xtr126** [comment]
I have tested it on a Android 12.1 Xiaomi device and Android 12 Samsung device and it does work. Both of the devices run custom OEM Android ROMs. Check the docs to get it running: https://xtr126.github.io/XtMapper-docs/guides/activation/#non-rooted-devices
Android 14 issues were fixed already. The app will install only on Android 9 and newer versions.
There is no warning to plug-in keyboard and mouse as it was assumed that user will have it always when designing the app for PCs.

**Comment by shirooo39** [comment]
> I have tested it on a Android 12.1 Xiaomi device and Android 12 Samsung device and it does work.

I tried it on crDroid running on top of Android 12.1 and it sort of work? the UI just doesn't fit at all, it's all mess. but again, I get that the app was meant to be used on a PC afterall.

anyway, thanks for the reply. I'll give it another try when I have the time.  
hopefully the keymapping would work nicely. it if could work at all, I don't mind about the interface at all.
