### ISSUE TITLE
[Feature Request] Custom DPAD keys

### ISSUE THREAD

**Issue by null2264** [Xtr126/XtMapper#87]
**Describe the issue**
Probably a bit niche, but it'd be nice to be able to use mixed of WASD keys and Arrow keys, my setup is Up arrow and Down arrow to move forward and backwards, and A D to move side to side.

Currently, I workaround it by remapping W and S to up and down arrow, but it's not ideal.

**Expected behavior**
Able to change DPAD keys.

**Device (please complete the following information):**
 - OS: ArchLinux (Linux 6.8.2-zen2-1-zen)
 - Android version: 11 (Waydroid)

**Comment by Xtr126** [comment]
Thanks for the suggestion, I will look into adding it if possible.
Swipe keys can also be used as an alternative in the meantime.

**Comment by Xtr126** [comment]
Closing this issue as dpad key remapping has been successfully implemented.

**Comment by null2264** [comment]
Nice, thank you!
