### ISSUE TITLE
A custom path to su

### ISSUE THREAD

**Issue by posix** [Xtr126/XtMapper#88]
I have a rooted android and have to hide su by renaming it.
Is it possible to add a setting that allows us to specify the path to su?

**Comment by Xtr126** [comment]
> I have a rooted android and have to hide su by renaming it. Is it possible to add a setting that allows us to specify the path to su?

I use libsu for the app so I'll have to look into how to specify a custom path for su if it even supports it. 
If you have SELinux in permissive mode, activation with command line will work: https://xtr126.github.io/XtMapper-docs/guides/activation/#activation-using-command 
For SELinux in enforcing, use adb and shizuku https://xtr126.github.io/XtMapper-docs/guides/activation/#non-rooted-devices
