### ISSUE TITLE
can't activate

### ISSUE THREAD

**Issue by Sanskuy75** [Xtr126/XtMapper#95]
why is it always like this?
![Screenshot_20240607-131233_Quickstep](https://github.com/Xtr126/XtMapper/assets/172011892/604bd37b-70d9-4a45-922e-c11fc14cfaae)

**Comment by Xtr126** [comment]
The script might be invalid, opening the app again should refresh it.
Or use the alternate method described in https://xtr126.github.io/XtMapper-docs/guides/activation/

**Comment by Sanskuy75** [comment]
![Screenshot_20240608-093522_Quickstep](https://github.com/Xtr126/XtMapper/assets/172011892/1cdf28f4-633c-415f-956d-9b177e1ab91d)
still can not
I'm using bliss OS 15.9 and xtmapper 2.1.5

**Comment by Xtr126** [comment]
> ![Screenshot_20240608-093522_Quickstep](https://private-user-images.githubusercontent.com/172011892/337827711-1cdf28f4-633c-415f-956d-9b177e1ab91d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTg2MTQsIm5iZiI6MTcxNzg1ODMxNCwicGF0aCI6Ii8xNzIwMTE4OTIvMzM3ODI3NzExLTFjZGYyOGY0LTYzM2MtNDE1Zi05NTZkLTliMTc3ZTFhYjkxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOFQxNDUxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjcwMGJkZTlkY2I1NjNlOGU1N2NkZDdjODExMWRkMTljYzRkOTVjMTk1NTZkMDRlNjE2Zjc3NGIxNzFkY2M3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mWEg4t3vG1kW5ZmbkNOFEWiWGQWwMPqJUyds9JEVrHM) still can not I'm using bliss OS 15.9 and xtmapper 2.1.5

Check logcat for any clues, run `logcat -c` before activation and `logcat -v color` after it says Killed.
It used to work fine in older Bliss versions (15.8,14.10.1,16.9). Maybe they broke something. I will have to check in new Bliss builds.

**Comment by Xtr126** [comment]
I tested and activation works fine with Bliss 15.9.1 release from 02-06-2024
