### ISSUE TITLE
This app can't seem to update anyway because of unmatched signatures for me(well, on Waydroid)

### ISSUE THREAD

**Issue by InternetRebelAKAQuachHungPhong** [Xtr126/XtMapper#97]
So, this is the second time I encountered this issue; in the first, I would have to uninstall the current version then install the newer one. When I try to update from 2.1.0 to 2.1.5 with Install on Waydroid, nothing happened; when I tried using ADB to install, here comes the log that show something about unmatched signature, like this:

![Screenshot from 2024-07-07 15-14-18](https://github.com/Xtr126/XtMapper/assets/127122104/41745dcc-896e-4fb5-9645-0fdbd0f2c4f0)

**Device (please complete the following information):**
 - OS: Ubuntu 24.04(Ubuntu desktop)
 - Android version: Android 11

(Anyway, by the way, I didn't find any more platform to discuss or say this yet, but I've been wondering if XtMapper would be able to...export control configs as some files, then can be imported in app or through adding these files in a certain directory, or would you mind pointing a way to copy the existing mapper files so they can be added to the same directory(like, is it in the app package name folder in ``data``). I also wish this XtMapper project get promoted and more popular, so it can like, get more interest, and community contributions as well, and possibly used on different kinds of Android installations(stock devices or virtual machines or sideloading…) alongside BlissOS.)

**Comment by Xtr126** [comment]
XtMapper switched from debug keys to release keys in v2.1.1 https://github.com/Xtr126/XtMapper/issues/79 so it can't be updated.
Importing/Exporting configs is definitely possible with the data format used by XtMapper. 
Currently you can backup the settings/profiles .xml files from /data/data/xtr.keymapper/ but it might not work for 2.1.0 -> 2.1.5 as there were some changes.
XtMapper does work fine using shizuku on non rooted samsung and xiaomi OEM devices which I have tested on.

**Comment by Xtr126** [comment]
Import/Export functionality has been added, it will be available in next release.
![IMG_20240815_223920_428](https://github.com/user-attachments/assets/62164f97-6c57-4e39-a337-28a31fe4e3c0)
