### ISSUE TITLE
[Feature Request] Add an option to switch mouse between touch and mouse passthrough

### ISSUE THREAD

**Issue by sudoharun** [Xtr126/XtMapper#99]
Currently any mouse/cursor input is received as a touch event. This feature would be nice to have since some Android games already have KBM support, such as Roblox and Minecraft. This is especially useful for applications such as Waydroid since the new implementation of [wayland-getevent](https://github.com/Xtr126/wayland-getevent) (which is [cage](https://github.com/Xtr126/cage)) does not separate the actual XtMapper input grabber as its own window.

 - OS: Waydroid + [Xtr126's implementation of cage](https://github.com/Xtr126/cage)
 - Android version 11

**Comment by Xtr126** [comment]
This is only needed for cage. On other systems pause keymap option works. It will have to be implemented in cage itself.

**Comment by Xtr126** [comment]
Update: Now you can switch with F11 key or any key defined in [togglekey.h](https://github.com/Xtr126/cage/blob/master/togglekey.h)
